<a href="https://colab.research.google.com/github/Gustavolobosolitario/Quake_Log_Parser/blob/master/C%C3%B3pia_de_Ol%C3%A1%2C_este_%C3%A9_o_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrudução

Desafio de Estágio em Data Engineering..


1. Qual a média de gastos de pessoas com ingresso Pista?
2. Quais pessoas não compareceram aos shows?
3. Quais pessoas compraram ingressos com concorrentes?
4. Qual o dia com maior gasto?
5. Faça uma lista com os clientes que desistiram de comprar o ingresso com a AT, a
soma do valor que foi gasto durante os shows e quais shows eles desistiram de
Descrição do código, do desafio...

##Importação das libs

In [1]:
import pandas as pd
import numpy as np
import json

#Importando dados

In [2]:
# dados de ingressos
df_ingressos = pd.read_json('https://us-central1-raccoon-bi.cloudfunctions.net/psel_de_ingressos')

# dados dos shows
df_shows = pd.read_json('https://us-central1-raccoon-bi.cloudfunctions.net/psel_de_shows')

# dados de compras
df_compras = pd.read_csv('https://us-central1-raccoon-bi.cloudfunctions.net/psel_de_compras')

In [3]:
# Visualizando dados de ingressos
df_ingressos.head()

    ano  dia  mes               nome                 status tipo
0  2020    1    1  Benjamin Mcdonald          Nao Concluido  VIP
1  2020    1    1   Mitchell Kostyla          Nao Concluido  VIP
2  2020    1    1       Gerald Allen          Nao Concluido  VIP
3  2020    1    1     Frederick Bank  Problema no Pagamento  VIP
4  2020    1    1           Tina Yee          Nao Concluido  VIP

In [4]:
# Visualizando dados dos shows
df_shows.head()

     Nascent Letter  Symbolic Toy  Terrestrial Chair
ano            2020          2020               2020
dia               2             3                  1
mes               1             1                  1

In [5]:
# Visualizando dados de compras
df_compras.head()

                 nome          show   gastos
0         Joseph Wray  Symbolic Toy  3142.35
1      Barbara Mcneil  Symbolic Toy  2431.78
2  Eduardo Espenshade  Symbolic Toy   386.32
3         Lucia Hayes  Symbolic Toy  3373.49
4     Johnny Hairston  Symbolic Toy  2805.88

In [6]:
# Pessoas Ingressos Pista
df_ingressos.loc[df_ingressos['tipo']=='Pista']

     ano  dia  mes               nome                 status   tipo
34  2020    1    1   Joshua Sanderson          Nao Concluido  Pista
35  2020    1    1          Donna Wal              Concluido  Pista
36  2020    1    1      Andrea Galyen          Nao Concluido  Pista
37  2020    1    1        Lyle Branch  Problema no Pagamento  Pista
38  2020    1    1       Debra Howard          Nao Concluido  Pista
39  2020    1    1       Debra Howard  Problema no Pagamento  Pista
40  2020    1    1     Daniel Puckett          Nao Concluido  Pista
41  2020    1    1  Gretchen Hinojosa              Concluido  Pista
42  2020    1    1    Suzanne Herring  Problema no Pagamento  Pista
43  2020    1    1       Jarrod Adler          Nao Concluido  Pista
44  2020    1    1  Gretchen Hinojosa          Nao Concluido  Pista
45  2020    1    1     Travis Whatley  Problema no Pagamento  Pista
46  2020    1    1     Elizabeth Daly  Problema no Pagamento  Pista
47  2020    2    1        Lyle Branch              Concluido  Pista
48  2020    2    1          Emil Nord          Nao Concluido  Pista
49  2020    2    1          John Rich  Problema no Pagamento  Pista
50  2020    2    1       James Reaves  Problema no Pagamento  Pista
51  2020    2    1        Frank Houck  Problema no Pagamento  Pista
52  2020    2    1          John Rich              Concluido  Pista
53  2020    2    1   Courtney Edwards              Concluido  Pista
54  2020    3    1  Richard Culpepper              Concluido  Pista
55  2020    3    1        Young Besaw              Concluido  Pista
56  2020    3    1        Lucia Hayes              Concluido  Pista
57  2020    3    1   Kelly Williamson  Problema no Pagamento  Pista
58  2020    3    1     Marcela Nelson              Concluido  Pista
59  2020    3    1      Sandra Duncan              Concluido  Pista
60  2020    3    1       Miguel Ramey              Concluido  Pista
61  2020    3    1      Nancy Degroot          Nao Concluido  Pista
62  2020    3    1       Edward Smith  Problema no Pagamento  Pista
63  2020    3    1   Mitchell Kostyla              Concluido  Pista

In [7]:
# União da tabela de ingressos e compras
df_ingressos_gastos = df_ingressos.merge(df_compras, on='nome', how = 'inner')
df_ingressos_gastos

,ano,dia,mes,nome,status,tipo,show,gastos
0,2020,1,1,Benjamin Mcdonald,Nao Concluido,VIP,Terrestrial Chair,2309.81
1,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,1731.06
2,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,2901.19
3,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,3091.97
4,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Nascent Letter,1658.48
...,...,...,...,...,...,...,...,...
372,2020,3,1,Joseph Wray,Problema no Pagamento,Pista Premium,Symbolic Toy,3142.35
373,2020,3,1,Barbara Mcneil,Concluido,Pista Premium,Symbolic Toy,2431.78
374,2020,3,1,Eduardo Espenshade,Concluido,Pista Premium,Symbolic Toy,386.32
375,2020,3,1,Richard Jimenez,Nao Concluido,Pista Premium,Symbolic Toy,1170.46
376,2020,3,1,Richard Jimenez,Nao Concluido,Pista Premium,Nascent Letter,3293.42

In [8]:
# Média de gastos de pessoas da pista
df_ingressos_gastos[df_ingressos_gastos['tipo']=='Pista']['gastos'].mean()

1792.6510204081637

In [9]:
# 3-Pessoas compraram ingressos com concorrentes
df_ingressos[df_ingressos['status']=='Nao Concluido']

     ano  dia  mes                nome         status           tipo
0   2020    1    1   Benjamin Mcdonald  Nao Concluido            VIP
1   2020    1    1    Mitchell Kostyla  Nao Concluido            VIP
2   2020    1    1        Gerald Allen  Nao Concluido            VIP
4   2020    1    1            Tina Yee  Nao Concluido            VIP
6   2020    1    1        Jeffrey Pace  Nao Concluido            VIP
8   2020    1    1      William Barnes  Nao Concluido            VIP
9   2020    1    1  Charles Hershenson  Nao Concluido            VIP
13  2020    1    1         Nancy Smith  Nao Concluido            VIP
14  2020    1    1      Donna Chandler  Nao Concluido            VIP
18  2020    2    1            Tina Yee  Nao Concluido            VIP
21  2020    2    1        Shayla Baird  Nao Concluido            VIP
22  2020    2    1    Kelly Williamson  Nao Concluido            VIP
23  2020    2    1       Edna Martinez  Nao Concluido            VIP
26  2020    2    1       Matt Smudrick  Nao Concluido            VIP
27  2020    2    1         Alice Gamba  Nao Concluido            VIP
31  2020    3    1       Andrea Galyen  Nao Concluido            VIP
32  2020    3    1       Yong Baltazar  Nao Concluido            VIP
34  2020    1    1    Joshua Sanderson  Nao Concluido          Pista
36  2020    1    1       Andrea Galyen  Nao Concluido          Pista
38  2020    1    1        Debra Howard  Nao Concluido          Pista
40  2020    1    1      Daniel Puckett  Nao Concluido          Pista
43  2020    1    1        Jarrod Adler  Nao Concluido          Pista
44  2020    1    1   Gretchen Hinojosa  Nao Concluido          Pista
48  2020    2    1           Emil Nord  Nao Concluido          Pista
61  2020    3    1       Nancy Degroot  Nao Concluido          Pista
66  2020    1    1        Blanche Knox  Nao Concluido  Pista Premium
67  2020    1    1      Michael Gaines  Nao Concluido  Pista Premium
79  2020    2    1    Mitchell Kostyla  Nao Concluido  Pista Premium
81  2020    2    1      Sabrina Graves  Nao Concluido  Pista Premium
84  2020    2    1   Margaret Robinson  Nao Concluido  Pista Premium
90  2020    3    1           John Rich  Nao Concluido  Pista Premium
95  2020    3    1     Richard Jimenez  Nao Concluido  Pista Premium

In [13]:
# 4- O dia com maior gasto
df_compras.groupby('show')['gastos'].sum()

show
Nascent Letter       269765.88
Symbolic Toy         330810.92
Terrestrial Chair    319930.31
Name: gastos, dtype: float64

In [36]:
#5- clientes que desistiram de comprar o ingresso com a AT
df_ingressos[df_ingressos['status']=='Nao Concluido']

     ano  dia  mes                nome         status           tipo
0   2020    1    1   Benjamin Mcdonald  Nao Concluido            VIP
1   2020    1    1    Mitchell Kostyla  Nao Concluido            VIP
2   2020    1    1        Gerald Allen  Nao Concluido            VIP
4   2020    1    1            Tina Yee  Nao Concluido            VIP
6   2020    1    1        Jeffrey Pace  Nao Concluido            VIP
8   2020    1    1      William Barnes  Nao Concluido            VIP
9   2020    1    1  Charles Hershenson  Nao Concluido            VIP
13  2020    1    1         Nancy Smith  Nao Concluido            VIP
14  2020    1    1      Donna Chandler  Nao Concluido            VIP
18  2020    2    1            Tina Yee  Nao Concluido            VIP
21  2020    2    1        Shayla Baird  Nao Concluido            VIP
22  2020    2    1    Kelly Williamson  Nao Concluido            VIP
23  2020    2    1       Edna Martinez  Nao Concluido            VIP
26  2020    2    1       Matt Smudrick  Nao Concluido            VIP
27  2020    2    1         Alice Gamba  Nao Concluido            VIP
31  2020    3    1       Andrea Galyen  Nao Concluido            VIP
32  2020    3    1       Yong Baltazar  Nao Concluido            VIP
34  2020    1    1    Joshua Sanderson  Nao Concluido          Pista
36  2020    1    1       Andrea Galyen  Nao Concluido          Pista
38  2020    1    1        Debra Howard  Nao Concluido          Pista
40  2020    1    1      Daniel Puckett  Nao Concluido          Pista
43  2020    1    1        Jarrod Adler  Nao Concluido          Pista
44  2020    1    1   Gretchen Hinojosa  Nao Concluido          Pista
48  2020    2    1           Emil Nord  Nao Concluido          Pista
61  2020    3    1       Nancy Degroot  Nao Concluido          Pista
66  2020    1    1        Blanche Knox  Nao Concluido  Pista Premium
67  2020    1    1      Michael Gaines  Nao Concluido  Pista Premium
79  2020    2    1    Mitchell Kostyla  Nao Concluido  Pista Premium
81  2020    2    1      Sabrina Graves  Nao Concluido  Pista Premium
84  2020    2    1   Margaret Robinson  Nao Concluido  Pista Premium
90  2020    3    1           John Rich  Nao Concluido  Pista Premium
95  2020    3    1     Richard Jimenez  Nao Concluido  Pista Premium