<a href="https://colab.research.google.com/github/Gustavolobosolitario/Quake_Log_Parser/blob/master/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#introdução

Projeto de Engenharia de Dados

1- Qual a média de gastos de pessoas com ingresso Pista?

2- Quais pessoas não compareceram aos shows?

3- Quais pessoas compraram ingressos com concorrentes?

4- Qual o dia com maior gasto?

5- Faça uma lista com os clientes que desistiram de comprar o ingresso com a AT, a soma do valor que foi gasto durante os shows e quais shows eles desistiram.

#Importação das libs

In [72]:
import pandas as pd
import numpy as np
import json

#Importando dados

In [73]:
# dados de ingressos
df_ingressos = pd.read_json('https://us-central1-raccoon-bi.cloudfunctions.net/psel_de_ingressos')

# dados dos shows
df_shows = pd.read_json('https://us-central1-raccoon-bi.cloudfunctions.net/psel_de_shows')

# dados de compras
df_compras = pd.read_csv('https://us-central1-raccoon-bi.cloudfunctions.net/psel_de_compras')

In [74]:
# Visualizando dados de ingressos
df_ingressos.head()

    ano  dia  mes               nome                 status tipo
0  2020    1    1  Benjamin Mcdonald          Nao Concluido  VIP
1  2020    1    1   Mitchell Kostyla          Nao Concluido  VIP
2  2020    1    1       Gerald Allen          Nao Concluido  VIP
3  2020    1    1     Frederick Bank  Problema no Pagamento  VIP
4  2020    1    1           Tina Yee          Nao Concluido  VIP

In [75]:
# Visualizando dados dos shows
df_shows.head()

     Nascent Letter  Symbolic Toy  Terrestrial Chair
ano            2020          2020               2020
dia               2             3                  1
mes               1             1                  1

In [76]:
# Visualizando dados de compras
df_compras.head()

                 nome          show   gastos
0         Joseph Wray  Symbolic Toy  3142.35
1      Barbara Mcneil  Symbolic Toy  2431.78
2  Eduardo Espenshade  Symbolic Toy   386.32
3         Lucia Hayes  Symbolic Toy  3373.49
4     Johnny Hairston  Symbolic Toy  2805.88

 # 1 - Qual a média de gastos de pessoas com ingresso Pista?

* Interpretou-se que o enunciado pede pessoas do tipo pista, porém não especifica se o status é concluido ou problema no pagamento ou não concluido.
* Concluindo que solicitam pessoas do tipo pista que apenas compraram com a plataforma AT.

In [97]:
df_ingressos_gastos[(df_ingressos_gastos['tipo']=='Pista')&(df_ingressos_gastos['status']=='Concluido')]

,ano,dia,mes,nome,status,tipo,show,gastos
181,2020,1,1,Donna Wal,Concluido,Pista,Symbolic Toy,2851.83
182,2020,1,1,Donna Wal,Concluido,Pista,Symbolic Toy,427.96
183,2020,1,1,Donna Wal,Concluido,Pista,Nascent Letter,2730.95
184,2020,1,1,Donna Wal,Concluido,Pista,Nascent Letter,3102.11
185,2020,1,1,Donna Wal,Concluido,Pista,Terrestrial Chair,2841.61
210,2020,1,1,Gretchen Hinojosa,Concluido,Pista,Terrestrial Chair,2867.60
220,2020,2,1,Lyle Branch,Concluido,Pista,Symbolic Toy,1503.41
221,2020,2,1,Lyle Branch,Concluido,Pista,Symbolic Toy,2666.89
222,2020,2,1,Lyle Branch,Concluido,Pista,Nascent Letter,3162.55
223,2020,2,1,Lyle Branch,Concluido,Pista,Terrestrial Chair,2474.61
245,2020,2,1,John Rich,Concluido,Pista,Symbolic Toy,1935.54
246,2020,2,1,John Rich,Concluido,Pista,Symbolic Toy,16.05
247,2020,2,1,John Rich,Concluido,Pista,Symbolic Toy,814.57
248,2020,2,1,John Rich,Concluido,Pista,Nascent Letter,2411.30
249,2020,2,1,John Rich,Concluido,Pista,Nascent Letter,1331.66
250,2020,2,1,John Rich,Concluido,Pista,Nascent Letter,421.03
251,2020,2,1,John Rich,Concluido,Pista,Nascent Letter,575.63
252,2020,2,1,John Rich,Concluido,Pista,Terrestrial Chair,1347.37
253,2020,2,1,John Rich,Concluido,Pista,Terrestrial Chair,129.45
254,2020,2,1,John Rich,Concluido,Pista,Terrestrial Chair,2901.19
255,2020,2,1,John Rich,Concluido,Pista,Terrestrial Chair,2714.06
256,2020,2,1,Courtney Edwards,Concluido,Pista,NaN,NaN
257,2020,3,1,Richard Culpepper,Concluido,Pista,Symbolic Toy,398.35
258,2020,3,1,Richard Culpepper,Concluido,Pista,Nascent Letter,2439.13
259,2020,3,1,Young Besaw,Concluido,Pista,Symbolic Toy,3086.46
260,2020,3,1,Young Besaw,Concluido,Pista,Symbolic Toy,2811.74
261,2020,3,1,Lucia Hayes,Concluido,Pista,Symbolic Toy,3373.49
270,2020,3,1,Marcela Nelson,Concluido,Pista,NaN,NaN
271,2020,3,1,Sandra Duncan,Concluido,Pista,NaN,NaN
272,2020,3,1,Miguel Ramey,Concluido,Pista,NaN,NaN
275,2020,3,1,Mitchell Kostyla,Concluido,Pista,Symbolic Toy,1731.06
276,2020,3,1,Mitchell Kostyla,Concluido,Pista,Symbolic Toy,2901.19
277,2020,3,1,Mitchell Kostyla,Concluido,Pista,Symbolic Toy,3091.97
278,2020,3,1,Mitchell Kostyla,Concluido,Pista,Nascent Letter,1658.48
279,2020,3,1,Mitchell Kostyla,Concluido,Pista,Nascent Letter,889.63
280,2020,3,1,Mitchell Kostyla,Concluido,Pista,Nascent Letter,3348.90
281,2020,3,1,Mitchell Kostyla,Concluido,Pista,Terrestrial Chair,1558.09
282,2020,3,1,Mitchell Kostyla,Concluido,Pista,Terrestrial Chair,2363.19
283,2020,3,1,Mitchell Kostyla,Concluido,Pista,Terrestrial Chair,386.05
284,2020,3,1,Mitchell Kostyla,Concluido,Pista,Terrestrial Chair,428.81

* Foi impresso tabela tipo pista.

In [78]:
# 1- Pessoas Ingressos Pista
df_ingressos.loc[df_ingressos['tipo']=='Pista']

     ano  dia  mes               nome                 status   tipo
34  2020    1    1   Joshua Sanderson          Nao Concluido  Pista
35  2020    1    1          Donna Wal              Concluido  Pista
36  2020    1    1      Andrea Galyen          Nao Concluido  Pista
37  2020    1    1        Lyle Branch  Problema no Pagamento  Pista
38  2020    1    1       Debra Howard          Nao Concluido  Pista
39  2020    1    1       Debra Howard  Problema no Pagamento  Pista
40  2020    1    1     Daniel Puckett          Nao Concluido  Pista
41  2020    1    1  Gretchen Hinojosa              Concluido  Pista
42  2020    1    1    Suzanne Herring  Problema no Pagamento  Pista
43  2020    1    1       Jarrod Adler          Nao Concluido  Pista
44  2020    1    1  Gretchen Hinojosa          Nao Concluido  Pista
45  2020    1    1     Travis Whatley  Problema no Pagamento  Pista
46  2020    1    1     Elizabeth Daly  Problema no Pagamento  Pista
47  2020    2    1        Lyle Branch              Concluido  Pista
48  2020    2    1          Emil Nord          Nao Concluido  Pista
49  2020    2    1          John Rich  Problema no Pagamento  Pista
50  2020    2    1       James Reaves  Problema no Pagamento  Pista
51  2020    2    1        Frank Houck  Problema no Pagamento  Pista
52  2020    2    1          John Rich              Concluido  Pista
53  2020    2    1   Courtney Edwards              Concluido  Pista
54  2020    3    1  Richard Culpepper              Concluido  Pista
55  2020    3    1        Young Besaw              Concluido  Pista
56  2020    3    1        Lucia Hayes              Concluido  Pista
57  2020    3    1   Kelly Williamson  Problema no Pagamento  Pista
58  2020    3    1     Marcela Nelson              Concluido  Pista
59  2020    3    1      Sandra Duncan              Concluido  Pista
60  2020    3    1       Miguel Ramey              Concluido  Pista
61  2020    3    1      Nancy Degroot          Nao Concluido  Pista
62  2020    3    1       Edward Smith  Problema no Pagamento  Pista
63  2020    3    1   Mitchell Kostyla              Concluido  Pista

* Interpretei que havia a necessidade da união das tabelas para assim tirar os gastos médios do tipo pista da tabela.

In [79]:
# 1- União da tabela de ingressos e compras
df_ingressos_gastos = df_ingressos.merge(df_compras, on='nome', how = 'left')
df_ingressos_gastos

,ano,dia,mes,nome,status,tipo,show,gastos
0,2020,1,1,Benjamin Mcdonald,Nao Concluido,VIP,Terrestrial Chair,2309.81
1,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,1731.06
2,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,2901.19
3,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,3091.97
4,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Nascent Letter,1658.48
...,...,...,...,...,...,...,...,...
403,2020,3,1,Richard Jimenez,Nao Concluido,Pista Premium,Nascent Letter,3293.42
404,2020,3,1,Curtis Hernandez,Problema no Pagamento,Pista Premium,NaN,NaN
405,2020,3,1,Alice Gamba,Concluido,Pista Premium,NaN,NaN
406,2020,3,1,Brenda Kozak,Problema no Pagamento,Pista Premium,NaN,NaN
407,2020,3,1,Robert Copenhaver,Concluido,Pista Premium,NaN,NaN

* Após a união das tabelas foi possível imprimir a média de gastos do tipo pista.

In [80]:
# 1 -Média de gastos de pessoas da pista
df_ingressos_gastos[df_ingressos_gastos['tipo']=='Pista']['gastos'].mean()

1792.651020408163

# 2- Quais pessoas não compareceram aos shows?

* Foi interpretado que foi pedido as pessoas que não compareceram ao show, porém que haviam comprado com a plataforma AT. Não necessariamente todos que compraram com a Plataforma AT foram aos shows.

In [98]:
lista_pessoas_nao_compareceram = df_ingressos_gastos[df_ingressos_gastos.status=='Concluido'][df_ingressos_gastos['gastos'].isnull()]['nome'].to_list()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [99]:
lista_pessoas_nao_compareceram

['Deborah Silsby',
 'Frances Lambert',
 'Courtney Edwards',
 'Marcela Nelson',
 'Sandra Duncan',
 'Miguel Ramey',
 'Ricardo Clasby',
 'Courtney Edwards',
 'Pamela Nixon',
 'Brenda Key',
 'Rick Fleishman',
 'Linda Batiz',
 'Alice Gamba',
 'Robert Copenhaver']

In [100]:
df_ingressos_gastos[df_ingressos_gastos['gastos'].isnull()]

,ano,dia,mes,nome,status,tipo,show,gastos
67,2020,1,1,Deborah Silsby,Concluido,VIP,NaN,NaN
68,2020,1,1,Nancy Smith,Nao Concluido,VIP,NaN,NaN
69,2020,1,1,Donna Chandler,Nao Concluido,VIP,NaN,NaN
137,2020,2,1,James Coffey,Problema no Pagamento,VIP,NaN,NaN
138,2020,2,1,Frances Lambert,Concluido,VIP,NaN,NaN
139,2020,2,1,Matt Smudrick,Nao Concluido,VIP,NaN,NaN
140,2020,2,1,Alice Gamba,Nao Concluido,VIP,NaN,NaN
176,2020,3,1,Yong Baltazar,Nao Concluido,VIP,NaN,NaN
177,2020,3,1,Elizabeth Daly,Problema no Pagamento,VIP,NaN,NaN
218,2020,1,1,Travis Whatley,Problema no Pagamento,Pista,NaN,NaN
219,2020,1,1,Elizabeth Daly,Problema no Pagamento,Pista,NaN,NaN
244,2020,2,1,Frank Houck,Problema no Pagamento,Pista,NaN,NaN
256,2020,2,1,Courtney Edwards,Concluido,Pista,NaN,NaN
270,2020,3,1,Marcela Nelson,Concluido,Pista,NaN,NaN
271,2020,3,1,Sandra Duncan,Concluido,Pista,NaN,NaN
272,2020,3,1,Miguel Ramey,Concluido,Pista,NaN,NaN
273,2020,3,1,Nancy Degroot,Nao Concluido,Pista,NaN,NaN
274,2020,3,1,Edward Smith,Problema no Pagamento,Pista,NaN,NaN
302,2020,1,1,Maria Villa,Problema no Pagamento,Pista Premium,NaN,NaN
303,2020,1,1,Ricardo Clasby,Concluido,Pista Premium,NaN,NaN
311,2020,1,1,Frank Houck,Problema no Pagamento,Pista Premium,NaN,NaN
312,2020,1,1,Courtney Edwards,Concluido,Pista Premium,NaN,NaN
322,2020,1,1,Pamela Nixon,Concluido,Pista Premium,NaN,NaN
323,2020,1,1,Brenda Key,Concluido,Pista Premium,NaN,NaN
366,2020,2,1,Rick Fleishman,Concluido,Pista Premium,NaN,NaN
367,2020,2,1,Linda Batiz,Concluido,Pista Premium,NaN,NaN
371,2020,2,1,Amy Mejia,Problema no Pagamento,Pista Premium,NaN,NaN
404,2020,3,1,Curtis Hernandez,Problema no Pagamento,Pista Premium,NaN,NaN
405,2020,3,1,Alice Gamba,Concluido,Pista Premium,NaN,NaN
406,2020,3,1,Brenda Kozak,Problema no Pagamento,Pista Premium,NaN,NaN
407,2020,3,1,Robert Copenhaver,Concluido,Pista Premium,NaN,NaN

# 3- Quais pessoas compraram ingressos com concorrentes?

* Foi filtrado da tabela o status não concluido.

In [101]:
# 3-Pessoas compraram ingressos com concorrentes
df_ingressos[df_ingressos['status']=='Nao Concluido']

     ano  dia  mes                nome         status           tipo
0   2020    1    1   Benjamin Mcdonald  Nao Concluido            VIP
1   2020    1    1    Mitchell Kostyla  Nao Concluido            VIP
2   2020    1    1        Gerald Allen  Nao Concluido            VIP
4   2020    1    1            Tina Yee  Nao Concluido            VIP
6   2020    1    1        Jeffrey Pace  Nao Concluido            VIP
8   2020    1    1      William Barnes  Nao Concluido            VIP
9   2020    1    1  Charles Hershenson  Nao Concluido            VIP
13  2020    1    1         Nancy Smith  Nao Concluido            VIP
14  2020    1    1      Donna Chandler  Nao Concluido            VIP
18  2020    2    1            Tina Yee  Nao Concluido            VIP
21  2020    2    1        Shayla Baird  Nao Concluido            VIP
22  2020    2    1    Kelly Williamson  Nao Concluido            VIP
23  2020    2    1       Edna Martinez  Nao Concluido            VIP
26  2020    2    1       Matt Smudrick  Nao Concluido            VIP
27  2020    2    1         Alice Gamba  Nao Concluido            VIP
31  2020    3    1       Andrea Galyen  Nao Concluido            VIP
32  2020    3    1       Yong Baltazar  Nao Concluido            VIP
34  2020    1    1    Joshua Sanderson  Nao Concluido          Pista
36  2020    1    1       Andrea Galyen  Nao Concluido          Pista
38  2020    1    1        Debra Howard  Nao Concluido          Pista
40  2020    1    1      Daniel Puckett  Nao Concluido          Pista
43  2020    1    1        Jarrod Adler  Nao Concluido          Pista
44  2020    1    1   Gretchen Hinojosa  Nao Concluido          Pista
48  2020    2    1           Emil Nord  Nao Concluido          Pista
61  2020    3    1       Nancy Degroot  Nao Concluido          Pista
66  2020    1    1        Blanche Knox  Nao Concluido  Pista Premium
67  2020    1    1      Michael Gaines  Nao Concluido  Pista Premium
79  2020    2    1    Mitchell Kostyla  Nao Concluido  Pista Premium
81  2020    2    1      Sabrina Graves  Nao Concluido  Pista Premium
84  2020    2    1   Margaret Robinson  Nao Concluido  Pista Premium
90  2020    3    1           John Rich  Nao Concluido  Pista Premium
95  2020    3    1     Richard Jimenez  Nao Concluido  Pista Premium

* Foi feita a união da tabela de compras com a tabela de ingressos, dessa forma foi impresso todas as pessoas que foram aos shows.

In [102]:
df = df_compras.merge(df_ingressos[df_ingressos.status=='Concluido'], on='nome', how = 'left')

In [103]:
df

,nome,show,gastos,ano,dia,mes,status,tipo
0,Joseph Wray,Symbolic Toy,3142.35,NaN,NaN,NaN,NaN,NaN
1,Barbara Mcneil,Symbolic Toy,2431.78,2020.0,3.0,1.0,Concluido,Pista Premium
2,Eduardo Espenshade,Symbolic Toy,386.32,2020.0,3.0,1.0,Concluido,Pista Premium
3,Lucia Hayes,Symbolic Toy,3373.49,2020.0,3.0,1.0,Concluido,Pista
4,Johnny Hairston,Symbolic Toy,2805.88,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
523,Cassandra Gonsalves,Terrestrial Chair,154.39,NaN,NaN,NaN,NaN,NaN
524,Christopher Mueller,Symbolic Toy,1797.44,NaN,NaN,NaN,NaN,NaN
525,Christopher Mueller,Nascent Letter,1511.91,NaN,NaN,NaN,NaN,NaN
526,Christopher Mueller,Nascent Letter,3439.69,NaN,NaN,NaN,NaN,NaN
527,Christopher Mueller,Nascent Letter,1635.48,NaN,NaN,NaN,NaN,NaN

* Foi filtrado somente as pessoas que não compraram com a plataforma AT, impresso em uma lista sem repetição de nomes.

In [104]:
df[df.status.isnull()].nome.unique()

array(['Joseph Wray', 'Johnny Hairston', 'James Bates', 'Karen Dumas',
       'Betty Moore', 'Jeffrey Ungaro', 'Willie Rodriguez',
       'Humberto Acton', 'Leonard Schwartz', 'Beverly Redfern',
       'Candy Killough', 'Henry Robinson', 'Scott Johnson',
       'Timothy Calles', 'Michael Keshishian', 'Derrick Collins',
       'Trina Meadows', 'Marian Jackson', 'Jane Dunlap', 'George Hamm',
       'Edward Scott', 'Lorene Phifer', 'Pamela Williams', 'Edward Dick',
       'Mayola Hall', 'Arthur Steiner', 'Lisa Flowers', 'James Bombard',
       'Paul Elliott', 'Robin Rossi', 'James Glover', 'Margaret Robinson',
       'Shayla Baird', 'Peggy Baughman', 'Kristal Mick', 'Tricia Mueller',
       'Sharon Marshall', 'Linda Harris', 'Anthony King', 'Craig Wrisley',
       'Pamela Brimmage', 'Lois Gaynor', 'Andrew Hoff', 'Alan Gravois',
       'Allison Magill', 'Gary Schulman', 'Brian Mann', 'Robin Bell',
       'Vicki Sanchez', 'Catherine Loos', 'Elena Lane', 'Jesse Sheehan',
       'Kathleen Nosal', 'Paul Brady', 'Danielle Gill', 'Dorothy Simmons',
       'Louis Dejong', 'Cheryl West', 'Carol Meeker', 'Richard Sharpe',
       'Maudie Cullen', 'Todd Mendoza', 'Juanita Grant',
       'Fannie Anderson', 'Pamela Isenhour', 'Jeanette Meyer',
       'Amanda Jones', 'James Mccollum', 'Leo Hall', 'Juan Koopman',
       'Jessie Cook', 'Catalina Berry', 'Veronica Mckinney',
       'Brittney Birkey', 'Maria Mccullar', 'Mathew Potter',
       'Richard Hau', 'Betty Lynch', 'William Converse',
       'Benjamin Mcdonald', 'Gerald Allen', 'Suzanne Herring',
       'Patrick Brown', 'Denise Trapp', 'Cynthia Daves', 'Patrick Luna',
       'Tony Dechant', 'Elizabeth Pietrowski', 'Frank Skeesick',
       'Earl Thoburn', 'Jayne Romaine', 'Jesus Blodgett',
       'Phyllis Patrick', 'Matthew Hammett', 'Donna Marinas',
       'Henry Martinez', 'Emilio Mccoy', 'Ramon Reed', 'Kevin Stafford',
       'Belen Bradley', 'Thomas Watts', 'Eileen Gonzalez', 'Francis Lowe',
       'Herman Severson', 'Elizabeth Barela', 'Albert Fadden',
       'Gary Baier', 'Mary Brooks', 'Lindsey Robertson',
       'Rebecca Burleson', 'William Polite', 'Alberto Gumm', 'Carol Eash',
       'John Mickle', 'Peter Acosta', 'Ruth Allbright', 'Bryan Rayford',
       'Violet Meek', 'Carl Weber', 'Lloyd Seifert', 'Richard Hale',
       'Jennifer Williams', 'Kenneth Lucas', 'Robert Boyle',
       'Walter Dodgen', 'Frances Williams', 'Courtney Chapman',
       'Robert Collins', 'Thomas Mitchem', 'Caleb Munselle',
       'Emily Reece', 'Emil Nord', 'Anna Hines', 'Beth Evans',
       'Bobby Rick', 'Monte Hahn', 'Opal Young', 'Sarah Cole',
       'Bruce Hicks', 'Jack Spilde', 'Jasmin Bray', 'Joann Hinde',
       'Laura Booth', 'Leon Poppel', 'Mark Mealer', 'Philip Webb',
       'Stella Shaw', 'Allen Bylsma', 'Benny Boisen', 'Blanche Knox',
       'Chris Wright', 'Debra Howard', 'Gilbert Romo', 'James Reaves',
       'Jarrod Adler', 'Jeffrey Pace', 'John Stowell', 'Larry Teague',
       'Micheal Hill', 'Miriam Price', 'Nancy Soolua', 'Oscar Kramer',
       'Philip Acuna', 'Walter Kelly', 'Adelina Thews', 'Andrea Galyen',
       'Anthony Nokes', 'Brandy Barnes', 'Dennis Miller', 'Edna Martinez',
       'Frank Davilla', 'Joseph Almond', 'Lenard Thomas', 'Luisa Pulliam',
       'Michael Moore', 'Rachel Hepler', 'Richard White', 'Ruby Richards',
       'Temple Barnes', 'William Swann', 'Chelsea Banter',
       'Chester Chavez', 'Clarence Sharp', 'Daniel Markell',
       'Daniel Puckett', 'Darrel Allmand', 'Jennifer Grant',
       'Jeremiah Hodge', 'Joshua Petzold', 'Kimberly Ferri',
       'Leonard Storey', 'Maria Marshall', 'Matthew Pfeiff',
       'Monica Mcclung', 'Sabrina Graves', 'Sherry Bremmer',
       'William Barnes', 'William Cotton', 'Donald Williams',
       'Jonathan Bechel', 'Kristen Okajima', 'Mark Radosevich',
       'Melissa Esparza', 'Richard Jimenez', 'Genoveva Poucher',
       'Joshua Sanderson', 'Kelly Williamson', 'Timothy Brackett',
       'Vicente Mcknight', 'David Pendergraph', 'Charles Hershenson',
       'Cassandra Gonsalves', 'Christopher Mueller'], dtype=object)

# 4- Qual o dia com maior gasto?

* Foi filtrado a soma de gastos dos três dias.

In [105]:
df_ingressos_gastos.groupby('dia')['gastos'].sum()

dia
1    258179.72
2    255496.88
3    158937.37
Name: gastos, dtype: float64

* Impresso o gasto total de cada dia em lista.

In [90]:
df_gastos_por_dia = pd.DataFrame(df_ingressos_gastos.groupby('dia')['gastos'].sum())

In [91]:
df_gastos_por_dia

        gastos
dia
1    258179.72
2    255496.88
3    158937.37

* Foi feito um index para saber que o dia que obteve mais gastos foi dia 1.

In [92]:
df_gastos_por_dia.index[df_gastos_por_dia.gastos==df_gastos_por_dia.gastos.max()].to_list()

[1]

#5- Faça uma lista com os clientes que desistiram de comprar o ingresso com a AT, a soma do valor que foi gasto durante os shows e quais shows eles desistiram.

In [96]:
#5- lista com os clientes que desistiram de comprar o ingresso com a AT
df_ingressos_gastos[df_ingressos_gastos['status'].isin(['Nao Concluido','Problema no Pagamento'])]

,ano,dia,mes,nome,status,tipo,show,gastos
0,2020,1,1,Benjamin Mcdonald,Nao Concluido,VIP,Terrestrial Chair,2309.81
1,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,1731.06
2,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,2901.19
3,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Symbolic Toy,3091.97
4,2020,1,1,Mitchell Kostyla,Nao Concluido,VIP,Nascent Letter,1658.48
...,...,...,...,...,...,...,...,...
399,2020,3,1,Joseph Wray,Problema no Pagamento,Pista Premium,Symbolic Toy,3142.35
402,2020,3,1,Richard Jimenez,Nao Concluido,Pista Premium,Symbolic Toy,1170.46
403,2020,3,1,Richard Jimenez,Nao Concluido,Pista Premium,Nascent Letter,3293.42
404,2020,3,1,Curtis Hernandez,Problema no Pagamento,Pista Premium,NaN,NaN
406,2020,3,1,Brenda Kozak,Problema no Pagamento,Pista Premium,NaN,NaN

In [93]:
df_final = df_ingressos_gastos[['nome', 'show', 'gastos']].dropna()

In [94]:
df_final

                   nome               show   gastos
0     Benjamin Mcdonald  Terrestrial Chair  2309.81
1      Mitchell Kostyla       Symbolic Toy  1731.06
2      Mitchell Kostyla       Symbolic Toy  2901.19
3      Mitchell Kostyla       Symbolic Toy  3091.97
4      Mitchell Kostyla     Nascent Letter  1658.48
..                  ...                ...      ...
399         Joseph Wray       Symbolic Toy  3142.35
400      Barbara Mcneil       Symbolic Toy  2431.78
401  Eduardo Espenshade       Symbolic Toy   386.32
402     Richard Jimenez       Symbolic Toy  1170.46
403     Richard Jimenez     Nascent Letter  3293.42

[377 rows x 3 columns]

* Foi impresso conforme a estrutura pedida.


{
"nome": <str>,
"gastos": <float>,
"shows": [<str>]
}

In [95]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377 entries, 0 to 403
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    377 non-null    object
 1   show    377 non-null    object
 2   gastos  377 non-null    float64
dtypes: float64(1), object(2)
memory usage: 11.8+ KB